### ISSUE TITLE
union types and matching their members?

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [peterhil/sagitta#1]
i just noticed this as a potentional next step

in particular since i'd like to handle cases like the Maybe Monad or protocol messages as such types

unfortunately there doesnt seem to be a nice syntax for whats

`data Maybe = Just a | Nothing`

in haskell

**Comment by peterhil** [comment]
I thought about that and also implementing the syntax by overloading the `|` (binary or) operator.
The overloading of `|` would only be done between arrows. See http://dev-tricks.net/pipe-infix-syntax-for-python

**Comment by peterhil** [comment]
The other thing I'd like to do next is to properly check and handle type variables like the `a` in `Just a`.

**Comment by RonnyPfannschmidt** [comment]
closing to get if off my plate on github
